---
- name: Playbook to Check Disk Space on Linux Servers
  hosts: all
  tasks:
  - name: Disk Space Usage Report on Servers
    shell: df -Th
    register: result

  - name: debug result
    debug:
     var: result.stdout_lines
    when: ansible_os_family == "Debian" 
