---
- name: installing nginx and checking diskspace
  hosts: group2
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: create file using shell
      shell: touch /tmp/ansible-test-file-1

- name: installing httpd in amazon linux machine
  hosts: group1
  become: true
  tasks:
   - name: Install apache
     dnf:
       name: httpd
       state: present
